const canvas=document.getElementById('gameCanvas');const ctx=canvas.getContext('2d');const players=[{x:50,y:canvas.height-60,width:40,height:40,speed:5,bullets:[],alive:!0,invincible:!1,invincibleTime:0,color:'red',controls:{up:'ArrowUp',down:'ArrowDown',left:'ArrowLeft',right:'ArrowRight',shoot:' '},score:0},{x:100,y:canvas.height-60,width:40,height:40,speed:5,bullets:[],alive:!0,invincible:!1,invincibleTime:0,color:'blue',controls:{up:'w',down:'s',left:'a',right:'d',shoot:' '},score:0}];const keys={};const enemies=[];let totalScore=0;let highScore=localStorage.getItem('highScore')?parseInt(localStorage.getItem('highScore')):0;let paused=!1;function drawPlayer(player){ctx.fillStyle=player.invincible?'rgba(255, 255, 255, 0.5)':player.color;ctx.fillRect(player.x,player.y,player.width,player.height);ctx.fillStyle='#fff';ctx.font='16px Arial';ctx.fillText(`Score: ${player.score}`,player.x,player.y-10)}
function drawHighScore(){ctx.fillStyle='#fff';ctx.font='20px Arial';ctx.fillText(`High Score: ${highScore}`,canvas.width/2,30)}
function drawBullets(player){player.bullets.forEach((bullet,bIndex)=>{ctx.fillStyle='yellow';ctx.fillRect(bullet.x,bullet.y,bullet.width,bullet.height);bullet.y-=bullet.speed;enemies.forEach((enemy,eIndex)=>{if(bullet.x<enemy.x+enemy.width&&bullet.x+bullet.width>enemy.x&&bullet.y<enemy.y+enemy.height&&bullet.y+bullet.height>enemy.y){enemies.splice(eIndex,1);player.bullets.splice(bIndex,1);player.score++;totalScore++;if(totalScore>highScore){highScore=totalScore;localStorage.setItem('highScore',highScore)}}});if(bullet.y<0)player.bullets.splice(bIndex,1);})}
function drawEnemies(){ctx.fillStyle='green';enemies.forEach((enemy,index)=>{ctx.fillRect(enemy.x,enemy.y,enemy.width,enemy.height);moveEnemy(enemy);checkCollisionWithPlayers(enemy,index)})}
function moveEnemy(enemy){const alivePlayers=players.filter(player=>player.alive);if(alivePlayers.length===0)return;let closestPlayer=null;let minDistance=Infinity;alivePlayers.forEach(player=>{const distance=Math.hypot(player.x-enemy.x,player.y-enemy.y);if(distance<minDistance){minDistance=distance;closestPlayer=player}});if(closestPlayer){const angle=Math.atan2(closestPlayer.y-enemy.y,closestPlayer.x-enemy.x);enemy.x+=enemy.speed*Math.cos(angle);enemy.y+=enemy.speed*Math.sin(angle)}}
function checkCollisionWithPlayers(enemy,enemyIndex){players.forEach((player,playerIndex)=>{if(player.alive&&!player.invincible&&player.x<enemy.x+enemy.width&&player.x+player.width>enemy.x&&player.y<enemy.y+enemy.height&&player.y+player.height>enemy.y){player.alive=!1;player.color='pink'}})}
function movePlayer(player){if(!player.alive)return;if(keys[player.controls.up]&&player.y>0)player.y-=player.speed;if(keys[player.controls.down]&&player.y+player.height<canvas.height)player.y+=player.speed;if(keys[player.controls.left]&&player.x>0)player.x-=player.speed;if(keys[player.controls.right]&&player.x+player.width<canvas.width)player.x+=player.speed}
function shoot(player){if(!player.alive||player.bullets.length>5)return;player.bullets.push({x:player.x+player.width/2-2.5,y:player.y,width:5,height:10,speed:7})}
function checkPlayerRevival(){players.forEach((player,index)=>{if(!player.alive){const otherPlayer=players[1-index];if(otherPlayer.alive&&otherPlayer.x<player.x+player.width&&otherPlayer.x+otherPlayer.width>player.x&&otherPlayer.y<player.y+player.height&&otherPlayer.y+otherPlayer.height>player.y){player.alive=!0;player.invincible=!0;player.invincibleTime=5000;player.color=index===0?'red':'blue'}}})}
function update(){ctx.clearRect(0,0,canvas.width,canvas.height);players.forEach(player=>{if(player.invincible){player.invincibleTime-=16;if(player.invincibleTime<=0){player.invincible=!1}}});players.forEach(drawPlayer);drawHighScore();players.forEach(player=>drawBullets(player));drawEnemies();players.forEach(movePlayer);checkPlayerRevival();requestAnimationFrame(update)}
document.addEventListener('keydown',(e)=>{keys[e.key]=!0;players.forEach((player,index)=>{if(e.key===player.controls.shoot){shoot(player)}})});document.addEventListener('keyup',(e)=>{keys[e.key]=!1});setInterval(()=>{const enemyWidth=40;const enemyHeight=40;const x=Math.random()*(canvas.width-enemyWidth);const speed=Math.random()*1.5+0.5;enemies.push({x,y:0,width:enemyWidth,height:enemyHeight,speed})},1000);update()