(()=>{const SHEET_API="https://script.google.com/macros/s/AKfycbxPD79NUFIKfLOpd_NV_b-fMF871pTh9JhUOdm-sEvnZ9vTAEInairArom1CQNfmGr9cw/exec";let audio=null;const qs=id=>document.getElementById(id);function play(src){if(audio)audio.pause();audio=new Audio(src);audio.loop=!0;audio.play().catch(()=>{})}
function unlockReal(){localStorage.setItem("SDSG","active");qs("instructions")?.remove();qs("premiumCodeSection")?.remove();if(typeof renderPremiumGames==="function")renderPremiumGames();play("music.mp3")}
function unlockFake(){if(typeof renderPremiumGames==="function")renderPremiumGames();play("music_x.mp3")}
function renderPremiumGames(){const container=document.getElementById("premiumGamesContainer");if(!container)return;container.innerHTML="";const premium=localStorage.getItem("SDSG")==="active";premiumGames.forEach(name=>{const btn=document.createElement("button");btn.textContent=name;if(premium){btn.className="unlocked";btn.disabled=!1;btn.onclick=()=>window.location.href=`assets/huh/stealer%20leave/there%20is%20nothing%20pay%20then%20you%20get/what%20are%20you%20doing/STOP/i%20cant%20understand/security%20left/${name}/run.html`}else{btn.className="locked";btn.disabled=!0}
container.appendChild(btn)})}
window.renderPremiumGames=renderPremiumGames;async function signup(){const username=qs("username")?.value.trim();const password=qs("password")?.value.trim();const code=qs("premiumCodeInput")?.value.trim();if(!username||!password||!code){alert("Fill all fields");return}
if(code==="SDSG.LATEST_XCODE"){unlockFake();alert("Fake premium unlocked!");return}
try{const res=await fetch(SHEET_API,{method:"POST",body:JSON.stringify({username,password,code,action:"signup"})});const data=await res.json();if(data.success){unlockReal();alert("Signup successful! Premium unlocked.")}else{alert(data.error)}}catch(e){console.error(e);alert("Failed to fetch server. Check deployment or URL.")}}
async function login(){const username=qs("username").value.trim();const password=qs("password").value.trim();if(!username||!password){alert("Enter username and password");return}
try{const res=await fetch(SHEET_API,{method:"POST",body:JSON.stringify({username,password,action:"login"})});const data=await res.json();if(data.success){unlockReal();alert("Login successful!")}else{alert(data.error)}}catch(e){console.error(e);alert("Server unreachable")}}
qs("signupBtn")?.addEventListener("click",signup);qs("loginBtn")?.addEventListener("click",login);qs("checkPaidBtn")?.addEventListener("click",()=>{localStorage.getItem("SDSG")==="active"?alert("Already premium"):alert("Not active")});qs("deact")?.addEventListener("click",()=>{localStorage.removeItem("SDSG");location.reload()});qs("copyEmailBtn")?.addEventListener("click",()=>{navigator.clipboard.writeText(qs("email-template").innerText);alert("Copied email template!")});if(localStorage.getItem("SDSG")==="active")unlockReal();else play("music_alt.mp3")})();renderPremiumGames()