const beta = true;document.addEventListener('DOMContentLoaded',()=>{const btn=document.getElementById('dwnld');const status=document.getElementById('status');const repoDescriptionEl=document.getElementById('repoDescription');const repoInfoContainer=document.getElementById('repoInfo');const localFilename='./SDSG-local.zip';const fallbackUrl='https://drive.google.com/file/d/19e4R1z6SzwXlGM_rBYfKCSesQn2TQjr2/view?usp=sharing';const readmeRawUrl='https://raw.githubusercontent.com/Mahdiisdumb/Project-SDSG/refs/heads/master/README.md';const REFRESH_INTERVAL_MS=5*60*1000;const INITIAL_BACKOFF_MS=2000;const MAX_BACKOFF_MS=5*60*1000;let backoffMs=INITIAL_BACKOFF_MS;let periodicTimer=null;let lastSuccessfulFetch=0;if(beta){document.querySelectorAll("audio").forEach(a=>{try{a.pause();a.src="";a.load()}catch{}});const originalCreateElement=document.createElement.bind(document);document.createElement=function(tag){const el=originalCreateElement(tag);if(tag&&tag.toLowerCase()==="audio")el.play=()=>{};return el};if(window.AudioContext||window.webkitAudioContext){const AC=window.AudioContext||window.webkitAudioContext;window.AudioContext=window.webkitAudioContext=function(){const ctx=new AC();ctx.resume=async()=>{};ctx.createOscillator=()=>({connect(){},start(){},stop(){}});return ctx}}
const betaAudio=new Audio("beta.mp3");betaAudio.loop=!0;betaAudio.volume=1.0;const playBeta=()=>{betaAudio.play().catch(()=>{});document.removeEventListener("click",playBeta);document.removeEventListener("keydown",playBeta)};playBeta();document.addEventListener("click",playBeta);document.addEventListener("keydown",playBeta)}
function ensureRefreshButton(){if(document.getElementById('refreshRepoBtn'))return;const refreshBtn=document.createElement('button');refreshBtn.id='refreshRepoBtn';refreshBtn.type='button';refreshBtn.textContent='Refresh repository info';refreshBtn.style.marginLeft='12px';refreshBtn.style.padding='6px 10px';refreshBtn.style.fontSize='13px';refreshBtn.addEventListener('click',async()=>{refreshBtn.disabled=!0;status.textContent='Refreshing repository info...';const ok=await performFetch();status.textContent=ok?'Repository info updated.':'Repository info refresh failed.';refreshBtn.disabled=!1});if(repoInfoContainer){repoInfoContainer.querySelector('strong')?.after(refreshBtn)}else{document.body.appendChild(refreshBtn)}}
async function fetchRepoDescription(){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);try{const res=await fetch(readmeRawUrl,{cache:'no-cache',signal:controller.signal});clearTimeout(timeout);if(!res.ok)throw new Error(`Fetch failed ${res.status}`);const text=await res.text();const paragraphs=text.split(/\r?\n\r?\n/).map(p=>p.trim()).filter(Boolean);const first=paragraphs.length?paragraphs[0]:text.trim().split(/\r?\n/)[0]||'';const cleaned=first.replace(/^#+\s*/,'').trim();if(repoDescriptionEl){repoDescriptionEl.textContent=cleaned||'No short description found in README.';const existingNote=repoDescriptionEl.parentNode.querySelector('.repo-note');if(existingNote)existingNote.remove();const note=document.createElement('div');note.className='repo-note';note.style.marginTop='8px';note.style.fontSize='13px';note.style.color='#555';note.textContent='This description was fetched from the project README to provide context for local vs web trade-offs.';repoDescriptionEl.parentNode.appendChild(note)}
if(/offline|local|assets|games/i.test(text)){const localAdvantages=document.getElementById('localAdvantages');if(localAdvantages&&!document.getElementById('repoContentAdvantage')){const li=document.createElement('li');li.id='repoContentAdvantage';li.innerHTML='<strong>Repository content:</strong> The repository includes assets and files that benefit from being stored locally to avoid network restrictions.';localAdvantages.appendChild(li)}}
lastSuccessfulFetch=Date.now();backoffMs=INITIAL_BACKOFF_MS;return!0}catch{clearTimeout(timeout);if(repoDescriptionEl&&!repoDescriptionEl.textContent.trim()){repoDescriptionEl.textContent='Could not load repository description. You can still download the local package below.'}
return!1}}
async function performFetch(){const ok=await fetchRepoDescription();if(!ok){const wait=Math.min(backoffMs,MAX_BACKOFF_MS);backoffMs=Math.min(backoffMs*2,MAX_BACKOFF_MS);setTimeout(()=>{performFetch()},wait)}
return ok}
function startPeriodicRefresh(){if(periodicTimer)return;periodicTimer=setInterval(()=>{if(Date.now()-lastSuccessfulFetch<Math.min(REFRESH_INTERVAL_MS,30000))return;performFetch()},REFRESH_INTERVAL_MS)}
function stopPeriodicRefresh(){if(periodicTimer){clearInterval(periodicTimer);periodicTimer=null}}
async function downloadUrl(url,suggestedName){try{const resp=await fetch(url);if(!resp.ok)throw new Error(`HTTP ${resp.status}`);const blob=await resp.blob();const a=document.createElement('a');const objectUrl=URL.createObjectURL(blob);a.href=objectUrl;a.download=suggestedName||'';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(objectUrl);return!0}catch{return!1}}
btn.addEventListener('click',async()=>{status.textContent='Preparing download...';const gotLocal=await downloadUrl(localFilename,'SDSG-local.zip');if(gotLocal){status.textContent='Download started: SDSG-local.zip';return}
status.textContent='Local package not found - falling back to repository archive.';const gotFallback=await downloadUrl(fallbackUrl,'Project-SDSG-master.zip');if(gotFallback){status.textContent='Fallback download started: Project-SDSG-master.zip';return}
status.textContent='Automatic download failed. Opening repository page in a new tab.';window.open(fallbackUrl,'_blank','noopener')});ensureRefreshButton();performFetch().then(ok=>{status.textContent=ok?'Repository info loaded.':'Repository info unavailable.';startPeriodicRefresh()})})