const beta=0;document.addEventListener('DOMContentLoaded',()=>{const btn=document.getElementById('dwnld');const status=document.getElementById('status');const repoDescriptionEl=document.getElementById('repoDescription');const repoInfoContainer=document.getElementById('repoInfo');const readmeRawUrl='https://raw.githubusercontent.com/Mahdiisdumb/Project-SDSG/refs/heads/master/README.md';const REFRESH_INTERVAL_MS=5*60*1000;const INITIAL_BACKOFF_MS=2000;const MAX_BACKOFF_MS=5*60*1000;let backoffMs=INITIAL_BACKOFF_MS;let periodicTimer=null;let lastSuccessfulFetch=0;if(beta){document.querySelectorAll("audio").forEach(a=>{try{a.pause();a.src="";a.load()}catch{}});const originalCreateElement=document.createElement.bind(document);document.createElement=function(tag){const el=originalCreateElement(tag);if(tag&&tag.toLowerCase()==="audio")el.play=()=>{};return el};if(window.AudioContext||window.webkitAudioContext){const AC=window.AudioContext||window.webkitAudioContext;window.AudioContext=window.webkitAudioContext=function(){const ctx=new AC();ctx.resume=async()=>{};ctx.createOscillator=()=>({connect(){},start(){},stop(){}});return ctx}}
const betaAudio=new Audio("beta.mp3");betaAudio.loop=!0;betaAudio.volume=1.0;const playBeta=()=>{betaAudio.play().catch(()=>{});document.removeEventListener("click",playBeta);document.removeEventListener("keydown",playBeta)};playBeta();document.addEventListener("click",playBeta);document.addEventListener("keydown",playBeta)}
function ensureRefreshButton(){if(document.getElementById('refreshRepoBtn'))return;const refreshBtn=document.createElement('button');refreshBtn.id='refreshRepoBtn';refreshBtn.type='button';refreshBtn.textContent='Refresh repository info';refreshBtn.style.marginLeft='12px';refreshBtn.style.padding='6px 10px';refreshBtn.style.fontSize='13px';refreshBtn.addEventListener('click',async()=>{refreshBtn.disabled=!0;status.textContent='Refreshing repository info...';const ok=await performFetch();status.textContent=ok?'Repository info updated.':'Repository info refresh failed.';refreshBtn.disabled=!1});if(repoInfoContainer){repoInfoContainer.querySelector('strong')?.after(refreshBtn)}else{document.body.appendChild(refreshBtn)}}
async function fetchRepoDescription(){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);try{const res=await fetch(readmeRawUrl,{cache:'no-cache',signal:controller.signal});clearTimeout(timeout);if(!res.ok)throw new Error(`Fetch failed ${res.status}`);const text=await res.text();let html=text.replace(/^### (.*)$/gm,'<h3>$1</h3>').replace(/^## (.*)$/gm,'<h2>$1</h2>').replace(/^# (.*)$/gm,'<h1>$1</h1>').replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\*(.*?)\*/g,'<em>$1</em>').replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2" target="_blank">$1</a>').replace(/^\s*-\s+(.*)$/gm,'<li>$1</li>').replace(/(\r?\n){2,}/g,'<br><br>');html=html.replace(/(<li>.*?<\/li>)/gs,'<ul>$1</ul>');if(repoDescriptionEl){repoDescriptionEl.innerHTML=html;const existingNote=repoDescriptionEl.parentNode.querySelector('.repo-note');if(existingNote)existingNote.remove();const note=document.createElement('div');note.className='repo-note';note.style.marginTop='8px';note.style.fontSize='13px';note.style.color='#555';note.textContent='This description was fetched from the project README.';repoDescriptionEl.parentNode.appendChild(note)}
lastSuccessfulFetch=Date.now();backoffMs=INITIAL_BACKOFF_MS;return!0}catch{clearTimeout(timeout);if(repoDescriptionEl&&!repoDescriptionEl.textContent.trim()){repoDescriptionEl.textContent='Could not load repository description.'}
return!1}}
async function performFetch(){const ok=await fetchRepoDescription();if(!ok){const wait=Math.min(backoffMs,MAX_BACKOFF_MS);backoffMs=Math.min(backoffMs*2,MAX_BACKOFF_MS);setTimeout(()=>{performFetch()},wait)}
return ok}
function startPeriodicRefresh(){if(periodicTimer)return;periodicTimer=setInterval(()=>{if(Date.now()-lastSuccessfulFetch<Math.min(REFRESH_INTERVAL_MS,30000))return;performFetch()},REFRESH_INTERVAL_MS)}
function stopPeriodicRefresh(){if(periodicTimer){clearInterval(periodicTimer);periodicTimer=null}}
btn.addEventListener('click',()=>{window.open('https://project-sdsg-installer.up.railway.app/','_blank','noopener')});ensureRefreshButton();performFetch().then(ok=>{status.textContent=ok?'Repository info loaded.':'Repository info unavailable.';startPeriodicRefresh()})})