const canvas=document.getElementById("introCanvas");const ctx=canvas.getContext("2d");canvas.width=window.innerWidth;canvas.height=window.innerHeight;const introMusic=document.getElementById("introMusic");const skidSound=document.getElementById("skidSound");const overlay=document.getElementById("startOverlay");function loadFrames(p){return p.map(s=>{const i=new Image();i.src=s;return i})}
const NUM_GAMES=1;const gameFrames=[];for(let i=1;i<=NUM_GAMES;i++){const img=new Image();img.src=`intro/${i}.png`;gameFrames.push(img)}
const runFrames=loadFrames(["intro/run1.png","intro/run2.png"]);const skidFrames=loadFrames(["intro/skid1.png","intro/skid2.png","intro/skid3.png"]);const jumpFrame=new Image();jumpFrame.src="intro/jump.png";const idleFrame=new Image();idleFrame.src="intro/idle.png";const logoImg=new Image();logoImg.src="intro/logo.jpeg";const totalIntro=12000;const stateDuration=totalIntro/6;let animationRunning=!1;let timer=0;let frameIndex=0;let frameDelay=0;let introEnded=!1;let logoShown=!1;const gameObjects=gameFrames.map(img=>({img,x:Math.random()*canvas.width,y:Math.random()*canvas.height,angle:Math.random()*Math.PI*2,scale:0.5+Math.random()*0.5,speed:0.005+Math.random()*0.01,alpha:0,fadeSpeed:0.002+Math.random()*0.003}));function drawBackground(){ctx.fillStyle="#000000";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle="#222222";ctx.lineWidth=2;const m=Math.min(canvas.width,canvas.height)/2;for(let r=50;r<m;r+=50){ctx.beginPath();ctx.arc(canvas.width/2,canvas.height/2,r,0,Math.PI*2);ctx.stroke()}}
function drawGameObjects(){gameObjects.forEach(o=>{ctx.save();ctx.translate(o.x+(o.img.width*o.scale)/2,o.y+(o.img.height*o.scale)/2);ctx.rotate(o.angle);ctx.globalAlpha=o.alpha;ctx.drawImage(o.img,-o.img.width*o.scale/2,-o.img.height*o.scale/2,o.img.width*o.scale,o.img.height*o.scale);ctx.restore();o.angle+=o.speed;o.scale*=0.995;if(timer<=totalIntro/2){o.alpha+=o.fadeSpeed;if(o.alpha>0.3)o.alpha=0.3}else{o.alpha-=o.fadeSpeed;if(o.alpha<0)o.alpha=0}})}
function easeOutQuad(t){return t*(2-t)}
function easeInQuad(t){return t*t}
function drawRun(x,y){frameDelay++;if(frameDelay>=12){frameIndex=(frameIndex+1)%runFrames.length;frameDelay=0}
ctx.drawImage(runFrames[frameIndex],x,y,160,160)}
function drawSkid(x,y,p){const i=Math.min(skidFrames.length-1,Math.floor(p*(skidFrames.length-0.01)));ctx.drawImage(skidFrames[i],x,y,160,160)}
overlay.addEventListener("click",()=>{overlay.style.display="none";animationRunning=!0;introMusic.currentTime=0;introMusic.play();skidSound.playedOnce=!1;timer=0;frameIndex=0;frameDelay=0;logoShown=!1;introEnded=!1;requestAnimationFrame(animate)});window.addEventListener("keydown",e=>{if(introEnded&&e.key==="Enter")window.location.href="./pai/load.html"});function animate(){if(!animationRunning)return;timer+=16.67;ctx.clearRect(0,0,canvas.width,canvas.height);drawBackground();drawGameObjects();if(timer<=stateDuration){let p=timer/stateDuration;let i=Math.floor(p*gameFrames.length);if(i>=gameFrames.length)i=gameFrames.length-1;ctx.globalAlpha=1;ctx.drawImage(gameFrames[i],canvas.width/2-250,canvas.height/2-140,500,280)}else if(timer<=stateDuration*2){let t=(timer-stateDuration)/stateDuration;let x=-200+easeOutQuad(t)*(canvas.width/2+120+200);drawRun(x,canvas.height/2+100)}else if(timer<=stateDuration*3){const skidDuration=stateDuration*0.5;let t=(timer-stateDuration*2)/skidDuration;if(t>1)t=1;let sx=canvas.width/2+120;let ex=canvas.width/2-80;let x=sx+easeInQuad(t)*(ex-sx);drawSkid(x,canvas.height/2+100,t);if(!skidSound.playedOnce){skidSound.currentTime=0;skidSound.play();skidSound.playedOnce=!0}}else if(timer<=stateDuration*4){let t=(timer-stateDuration*3)/stateDuration;let y=canvas.height/2+100-Math.sin(t*Math.PI)*120;ctx.drawImage(jumpFrame,canvas.width/2-80,y,160,160);if(t>=0.5&&!logoShown)logoShown=!0;if(logoShown)ctx.drawImage(logoImg,canvas.width/2-250,140,500,250);}else{ctx.drawImage(logoImg,canvas.width/2-250,140,500,250);const pulse=1+Math.sin(timer/600)*0.015;const iw=160*pulse;const ih=160*pulse;ctx.drawImage(idleFrame,canvas.width/2-iw/2,canvas.height/2-ih/2,iw,ih);introEnded=!0;ctx.fillStyle="white";ctx.font="28px Arial";ctx.textAlign="center";ctx.fillText("Press Enter to continue",canvas.width/2,canvas.height-60)}
requestAnimationFrame(animate)}