const canvas=document.getElementById("introCanvas");const ctx=canvas.getContext("2d");canvas.width=window.innerWidth;canvas.height=window.innerHeight;const introMusic=document.getElementById("introMusic");const skidSound=document.getElementById("skidSound");const overlay=document.getElementById("startOverlay");function loadFrames(arr){return arr.map(src=>{const i=new Image();i.src=src;return i})}
const NUM_GAMES=8;const gameFrames=[];for(let i=1;i<=NUM_GAMES;i++){const img=new Image();img.src=`intro/${i}.png`;gameFrames.push(img)}
const runFrames=loadFrames(["intro/run1.png","intro/run2.png"]);const skidFrames=loadFrames(["intro/skid1.png","intro/skid2.png","intro/skid3.png"]);const jumpFrame=new Image();jumpFrame.src="intro/jump.png";const idleFrame=new Image();idleFrame.src="intro/idle.png";const logoImg=new Image();logoImg.src="intro/Logo.png";const TOTAL_DURATION=12516;const GAMES_END=4000;const MAHDI_END=7000;let animationRunning=!1;let frameIndex=0;let frameDelay=0;let introEnded=!1;const particles=[];const gameObjects=gameFrames.map(img=>({img,x:Math.random()*canvas.width,y:Math.random()*canvas.height,angle:Math.random()*Math.PI*2,scale:0.6+Math.random()*0.5,speed:0.01+Math.random()*0.02,alpha:0}));function spawnParticle(x,y){particles.push({x,y,vx:(Math.random()-0.5)*4,vy:-Math.random()*2,alpha:1,size:4+Math.random()*4})}
function drawParticles(){particles.forEach((p,i)=>{ctx.fillStyle=`rgba(255,255,255,${p.alpha})`;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill();p.x+=p.vx;p.y+=p.vy;p.alpha-=0.02;if(p.alpha<=0)particles.splice(i,1);})}
function drawBackground(){ctx.fillStyle="#000";ctx.fillRect(0,0,canvas.width,canvas.height)}
function drawGameObjects(progress){gameObjects.forEach(o=>{o.alpha=0.35*(1-progress);ctx.save();ctx.globalAlpha=o.alpha;ctx.translate(o.x,o.y);ctx.rotate(o.angle);ctx.drawImage(o.img,-o.img.width*o.scale/2,-o.img.height*o.scale/2,o.img.width*o.scale,o.img.height*o.scale);ctx.restore();o.angle+=o.speed})}
function easeOutExpo(t){return t===1?1:1-Math.pow(2,-10*t)}
function easeInExpo(t){return t===0?0:Math.pow(2,10*(t-1))}
function drawRun(x,y){frameDelay++;if(frameDelay>=2){frameIndex=(frameIndex+1)%runFrames.length;frameDelay=0}
for(let i=0;i<2;i++)spawnParticle(x+90,y+160);ctx.drawImage(runFrames[frameIndex],x,y,180,180)}
function drawSkid(x,y,p){const i=Math.min(skidFrames.length-1,Math.floor(p*(skidFrames.length-0.01)));for(let j=0;j<4;j++)spawnParticle(x+100,y+180);ctx.drawImage(skidFrames[i],x,y,200,200)}
async function checkBan(){if(!location.href.startsWith("https://"))return;const localIdKey="sdsg_user_id";let userId=localStorage.getItem(localIdKey);if(!userId){userId="user_"+Math.random().toString(36).slice(2,10);localStorage.setItem(localIdKey,userId)}
try{const res=await fetch("https://sdsg-bansystem.up.railway.app/check",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:userId})});const data=await res.json();if(data.banned){alert("You have been banned from SDSG. You need the local version or wait a day.");window.location.href="./banned/run.html"}}catch(err){console.error("Ban check failed:",err)}}
checkBan().then(()=>{overlay.addEventListener("click",()=>{overlay.style.display="none";introMusic.currentTime=0;skidSound.playedOnce=!1;introMusic.play();animationRunning=!0;introEnded=!1;frameIndex=0;frameDelay=0;requestAnimationFrame(animate)})});window.addEventListener("keydown",e=>{if(introEnded&&e.key==="Enter"){window.location.href="./pai/load.html"}});function animate(){if(!animationRunning)return;const t=introMusic.currentTime*1000;ctx.clearRect(0,0,canvas.width,canvas.height);drawBackground();drawParticles();if(t<=GAMES_END){const progress=t/GAMES_END;drawGameObjects(progress)}else if(t<=MAHDI_END){const sectionTime=t-GAMES_END;const duration=MAHDI_END-GAMES_END;const p=sectionTime/duration;if(p<=0.33){const rp=p/0.33;const x=-400+easeOutExpo(rp)*(canvas.width/2+400);const yOffset=-Math.sin(rp*Math.PI)*15;drawRun(x,canvas.height/2+80+yOffset)}else if(p<=0.66){if(!skidSound.playedOnce){skidSound.currentTime=0;skidSound.play();skidSound.playedOnce=!0}
const sp=(p-0.33)/0.33;const sx=canvas.width/2+240;const ex=canvas.width/2-160;const x=sx+easeInExpo(sp)*(ex-sx);const yOffset=Math.sin(sp*Math.PI)*20;drawSkid(x,canvas.height/2+80+yOffset,sp)}else{const jp=(p-0.66)/0.34;const y=canvas.height/2+80-Math.sin(jp*Math.PI)*300;const tilt=Math.sin(jp*Math.PI)*0.25;ctx.save();ctx.translate(canvas.width/2,y+110);ctx.rotate(tilt);ctx.drawImage(jumpFrame,-110,-110,220,220);ctx.restore();if(jp>0.3)ctx.drawImage(logoImg,canvas.width/2-260,120,520,260);}}else{ctx.drawImage(logoImg,canvas.width/2-260,120,520,260);const pulse=1+Math.abs(Math.sin(t*0.02))*0.08;const size=200*pulse;ctx.drawImage(idleFrame,canvas.width/2-size/2,canvas.height/2-size/2,size,size);ctx.fillStyle="white";ctx.font="32px Arial";ctx.textAlign="center";ctx.fillText("Press Enter to continue",canvas.width/2,canvas.height-60);ctx.fillText("©Mahdi_Studios (Division_WEB)",canvas.width/2,canvas.height-25);introEnded=!0}
if(t<TOTAL_DURATION)requestAnimationFrame(animate);}